
services:
  # ====================
  # MINDSDB AI/ML SERVICE
  # ====================
  
  mindsdb:
    build: .
    container_name: xplaincrypto-mindsdb
    ports:
      - "47334:47334"
      - "47335:47335" 
      - "47336:47336"
      - "47337:47337"
    volumes:
      # Critical: MindsDB storage persistence - FIXED PATH
      - mindsdb_storage:/root/mdb_storage
      # Secrets mounting (read-only)
      - ./secrets:/run/secrets:ro
    environment:
      - PYTHONUNBUFFERED=1
      
      # Redis Configuration (shared cache)
      - REDIS_HOST=xplaincrypto-redis
      - REDIS_PORT=6379
      - REDIS_DB=0                    # MindsDB uses DB 0
      - REDIS_PASSWORD=redis_secure_pass_dev123
      
      # Crypto Database (MindsDB AI/ML data) - CORRECTED
      - POSTGRES_HOST=142.93.49.20       # Server IP
      - POSTGRES_PORT=5432               # External port
      - POSTGRES_DB=crypto_data       # FIXED: Actual database name
      - POSTGRES_USER=mindsdb         # FIXED: Actual username
      
      # Users Database - TRY INTERNAL HOSTNAME
      - POSTGRES_USERS_HOST=postgres-users     # Service name from infra
      - POSTGRES_USERS_PORT=5432              # Internal port
      - POSTGRES_USERS_DB=user_data
      - POSTGRES_USERS_USER=xplaincrypto
      
      # FastAPI Database - TRY INTERNAL HOSTNAME  
      - POSTGRES_FASTAPI_HOST=postgres-fastapi # Service name from infra
      - POSTGRES_FASTAPI_PORT=5432            # Internal port
      - POSTGRES_FASTAPI_DB=operational_data
      - POSTGRES_FASTAPI_USER=fastapi
      
    networks:
      - xplaincrypto_network          # Explicit network assignment
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:47334/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5

# ====================
# SECRETS CONFIGURATION
# ====================

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
  openai_api_key:
    file: ./secrets/openai_api_key.txt
  anthropic_api_key:
    file: ./secrets/anthropic_api_key.txt
  timegpt_api_key:
    file: ./secrets/timegpt_api_key.txt
  coinmarketcap_api_key:
    file: ./secrets/coinmarketcap_api_key.txt
  dune_api_key:
    file: ./secrets/dune_api_key.txt
  coingecko_api_key:
    file: ./secrets/coingecko_api_key.txt
  whale_alerts_api_key:
    file: ./secrets/whale_alerts_api_key.txt

# ====================
# VOLUMES
# ====================

volumes:
  mindsdb_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/xplaincrypto/mindsdb

# ====================
# NETWORKS - CONNECT TO EXISTING INFRASTRUCTURE
# ====================

networks:
  xplaincrypto_network:
    external: true
    name: xplaincrypto-infra_xplaincrypto_network